name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DEV_PACKAGES: build-essential musl musl-dev musl-tools libssl-dev pkg-config
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Fetch DVC Fixtures
        run: cd tests && dvc pull && cd ..
      - name: Check DVC contents
        run: ls tests/solidity-fixtures
