name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DEV_PACKAGES: build-essential musl musl-dev musl-tools libssl-dev pkg-config
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Fetch DVC Fixtures
        run: dvc pull -R
      - name: Check DVC contents
        run: ls tests/solidity-fixtures
